### ISSUE TITLE
Change color of orange portal marker instead of displaying dots above orange portal marker

### ISSUE THREAD

**Issue by lollercopter** [EisFrei/IngressPortalHistoryFlags#2]
To make the map less cluttered, can you change the color of the orange/blue/green portal marker to be purple or red instead?

Or instead of displaying a solid purple or red dot, you could display a dot that has both orange/blue/green and purple/red along the edge. You could change the color every 45 degrees around the circle.

**Comment by Temetz** [comment]
Tried out something similar myself. Makes it visually a bit easier to read i think.
![image](https://user-images.githubusercontent.com/8721037/107164810-3db3ec80-69b9-11eb-9ad2-e1d638391ed2.png)

**Comment by Temetz** [comment]
Also something like this would be possible:
![image](https://user-images.githubusercontent.com/8721037/107164944-ccc10480-69b9-11eb-8e45-3e04bb701245.png)

**Comment by EisFrei** [comment]
I like it. I'll look into it

**Comment by Temetz** [comment]
Used the images from original intel:

https://commondatastorage.googleapis.com/ingress.com/img/map_icons/marker_images/layer_visited.png
https://commondatastorage.googleapis.com/ingress.com/img/map_icons/marker_images/layer_captured.png
https://commondatastorage.googleapis.com/ingress.com/img/map_icons/marker_images/layer_scanned.png

Then had these css styles:

```
.uniques-icon-visited { clip-path: polygon(50% 0, 100% 0, 100% 80%, 50% 50%); }
.uniques-icon-captured { clip-path: polygon(51% 50%, 100% 78%, 100% 100%, 0 100%, 0 80%);
.uniques-icon-scanned { clip-path: polygon(51% 51%, 51% 0, 0 0, 0 81%); }
```

**Comment by EisFrei** [comment]
The display has been changed to concentric circle arcs, but it uses svgs instead of pngs.
