### ISSUE TITLE
TypeError: window.getCurrentZoomTileParameters is not a function

### ISSUE THREAD

**Issue by Temetz** [EisFrei/IngressPortalHistoryFlags#4]
Bug: No markers are displayed on the map and the following error can be seen in the console:

`error running hook portalAdded, error: TypeError: window.getCurrentZoomTileParameters is not a function`

This bug seems to be introduced in this commit: https://github.com/EisFrei/IngressPortalHistoryFlags/commit/97131707cd354f52ca7023d68dd40d9df495f9de#diff-39af415773b0990d9ca02564dc6f6f1ad7a7c9197b85a2fd96cf2f742d8aed0aR59

**Comment by EisFrei** [comment]
I cannot reproduce this error. 
Does it always occur or just sometimes?
What's your setup?

**Comment by Yvandra** [comment]
I've had this bug, too. 
It occured with the basic iitc.me (IITC: Ingress intel map total conversion 0.26.0.20170108.21732), now I installed iitc.app and the history plugin works fine.

**Comment by Temetz** [comment]
Running on the iitc.me version as well. Havent tried the app.

**Comment by Temetz** [comment]
With IITC.me version the function you are looking for is most likely: `window.getMapZoomTileParameters()`
